### ISSUE TITLE
question - diffent mechanism other than Alexa

### ISSUE THREAD

**Issue by mihai-satmarean** [goruck/smart-zoneminder#1]
Hi,
I find your project very nice, and inspiring.
We are working to have a remote IP camera to detect when someone is chasing away some animals from the feeding place. 
The Alexa path is too much for our setup, but the rest seems very similar with our concept.
We are also working on automating the zone minder installation and configuration.
Would you find it difficult to add or suggest a choice for e-mail (or extendable to SMS who knows what) message instead of Alexa integration when an alert was triggered?
We have a working sample code that for now looks in to the image to see if there is an animal or a person.
We only want e-mail when one of the conditions is true, and the image with the boxes around the objects.
Thanks!

**Comment by goruck** [comment]
Hi,

thanks for the question. Your project sounds very interesting.

Yes, adding the feature to send an email when an alarm condition is detected is very straightforward. This could be done by adding another AWS lambda function that uses Amazon Simple Email Service and changing the Step state machine code to trigger that lambda function when the alarm condition is met. I actually have prototyped this code. I will add it as an option to this project. Thanks for the suggestion and do let me know if you have any further question!

Regards,

Lindo

**Comment by mihai-satmarean** [comment]
Glad to help and participate!

**Comment by goruck** [comment]
smart-zoneminder now supports emailing of alarms. See [nodemailer-send-notification](https://github.com/goruck/smart-zoneminder/tree/master/aws-lambda/nodemailer-send-notification).
