### ISSUE TITLE
Security suggestion

### ISSUE THREAD

**Issue by pbran** [goruck/smart-zoneminder#2]
This is a great project which I'm going to implement at least in part on my zoneminder setup.
Can I make a security suggestion?
Your bucket policy makes the bucket open to the world.
I have created a user specifically for the camera access and given it specific access to the ZM frames bucket and contents. The credentials granted to that user can be used in the application to upload the frames and via the console logging in as that user to view the frames.

Create another user.
IAM -> Users -> Add User -> Access type -> check Programmatic access and AWS Management Console Access
On the last step click on Download .csv file and save the file
Add permissions to the user
IAM -> Users -> your_user -> Permissions tab ->  +Add inline policy -> Custom policy
Copy and paste the following JSON and then give your inline policy a name

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowCamUsertoListS3BucketsInManagementConsole",
            "Action": [
                "s3:ListAllMyBuckets",
                "s3:GetBucketLocation"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::*"
            ]
        },
        {
            "Sid": "AllowCamUserRootLevelListingofThisBucket",
            "Action": [
                "s3:ListBucket"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::zm-alarm-frames-my-bucket”
            ]
        },
        {
            "Sid": "AllowCamUserFullAccessToS3zmalarmframesdevnull",
            "Action": [
                "s3:*"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::zm-alarm-frames-my-bucket”,
                "arn:aws:s3:::zm-alarm-frames-my-bucket/*”
            ]
        }
    ]
}

**Comment by goruck** [comment]
Thanks @pbran! I've changed the uploader app and updated the READMEs to reflect correct S3 permissions. See https://github.com/goruck/smart-zoneminder/commit/4651a480719e9b322b94a328d7576a6c27d9b89e and https://github.com/goruck/smart-zoneminder/commit/655224453cd236711de0f15638333a1ee8b26298.
